In [1]:
import numpy as np

In [12]:
test = np.zeros([1,3])

In [13]:
test

array([[0., 0., 0.]])

In [14]:
np.shape(test)

(1, 3)

In [9]:
print(test)

[10]


In [18]:
test = np.array(np.random.randint(0,100,50))

In [19]:
test

array([56, 93, 65, 97, 69, 60, 37, 39, 25, 43, 91, 62, 56, 27, 28,  6, 71,
       85, 64, 50,  3, 36, 56, 36, 73, 41, 78, 34, 38, 48, 93, 36, 45, 62,
       31, 41,  8, 97, 15, 74, 26, 71,  1, 39, 92, 17, 15, 32, 82,  7])

In [20]:
np.shape(test)

(50,)

In [21]:
test[:1]

array([56])

In [22]:
test[1:]

array([93, 65, 97, 69, 60, 37, 39, 25, 43, 91, 62, 56, 27, 28,  6, 71, 85,
       64, 50,  3, 36, 56, 36, 73, 41, 78, 34, 38, 48, 93, 36, 45, 62, 31,
       41,  8, 97, 15, 74, 26, 71,  1, 39, 92, 17, 15, 32, 82,  7])